apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-parcelize'

def media3_version = '1.11.1'

android {
    def versionProps = new Properties()
    def versionPropsFile = file('version.prop')
    def versionPropsCode = 1

    if (versionPropsFile.canRead()) {
        versionProps.load(new FileInputStream(versionPropsFile))
        versionPropsCode = (versionProps['VERSION_CODE'] ?: "1").toInteger()
    }

    compileSdk 37

    defaultConfig {
        applicationId "net.harimurti.tv"

        minSdk 23
        targetSdk 37

        versionCode versionPropsCode
        versionName "3.0.0"

        multiDexEnabled true
        vectorDrawables.useSupportLibrary true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        dataBinding true
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false

            proguardFiles(
                    getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
            )

            applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName =
                            "${defaultConfig.applicationId}_v${defaultConfig.versionName}_b${defaultConfig.versionCode}.apk"
                }
            }
        }
    }
}

dependencies {
    implementation fileTree(
            dir: 'libs',
            include: ['*.jar']
    )

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    implementation 'com.google.android.material:material:1.13.0'

    implementation 'com.squareup.okhttp3:okhttp:3.12.13'

    implementation "androidx.media3:media3-exoplayer:$media3_version"
    implementation "androidx.media3:media3-exoplayer-dash:$media3_version"
    implementation "androidx.media3:media3-exoplayer-rtsp:$media3_version"
    implementation "androidx.media3:media3-ui:$media3_version"

    implementation 'com.google.android.gms:play-services-auth:19.2.0'
    implementation 'com.google.code.gson:gson:2.13.1'

    implementation 'com.github.TutorialsAndroid:FilePicker:v8.0.19'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    implementation 'com.h6ah4i.android.widget.verticalseekbar:verticalseekbar:1.0.0'

    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
